/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <setjmp.h>
#include <stdio.h>
#include "unity.h"

char MessageBuffer[50];

extern void test_mlx_logger();
extern void setUp(void);
extern void tearDown(void);


static void runTest(UnityTestFunction test)
{
  {
      setUp();
      test();
  }
  if (TEST_PROTECT() && !TEST_IS_IGNORED)
  {
    tearDown();
  }
}
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


int main(void)
{
  UnityBegin("test_mlx_logger.c");

  // RUN_TEST calls runTest
  RUN_TEST(test_mlx_logger);

  UnityEnd();
  return 0;
}
